name: Release Suite

on:
  push:
    tags:
      - v0.*
      - v1.*
    branches:
      - fix_release_action



env:
  AUTOINSTALL: true
  VERBOSE: true
  CI: true
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-x86_64-unknown-linux-musl-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - run: make ci-sweep
      - env:
          PASS_FEATURES: "default-cmake"
        run: make package-x86_64-unknown-linux-musl-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl.tar.gz"

  build-x86_64-unknown-linux-gnu-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          PASS_FEATURES: "default"
        run: make package-x86_64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm"

  build-aarch64-unknown-linux-musl-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
          PASS_FEATURES: "default-cmake"
        run: make package-aarch64-unknown-linux-musl-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl.tar.gz"

  build-aarch64-unknown-linux-gnu-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
          PASS_FEATURES: "default"
        run: make package-aarch64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm64.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-arm64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.aarch64.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.aarch64.rpm"

  build-armv7-unknown-linux-gnueabihf-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-gnueabihf-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armhf.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armhf.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.armv7.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.armv7.rpm"

  build-armv7-unknown-linux-musleabihf-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - run: make ci-sweep
      - env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-musleabihf
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf.tar.gz"

  build-x86_64-apple-darwin-packages:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: "Upgrade bash"
        run: brew install bash
      - name: "Install realpath dependency"
        run: brew install coreutils
      - name: Add version variable
        run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
        shell: bash
      - name: "Build archive"
        env:
          TARGET: "x86_64-apple-darwin"
          NATIVE_BUILD: true
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          make package
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-apple-darwin.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-apple-darwin.tar.gz"

  build-x86_64-pc-windows-msvc-packages:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: "Add Vector version"
        run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
        shell: bash
      - name: "Download Perl"
        shell: bash
        env:
          VERSION: "5.32.0.1"
        run: |
          curl -sSfL https://strawberryperl.com/download/$VERSION/strawberry-perl-$VERSION-64bit.msi > perl-installer.msi
      - name: "Install Perl"
        shell: cmd # msiexec fails when called from bash
        run: |
          msiexec /quiet /i perl-installer.msi
          del perl-installer.msi
      - name: "Download CMake"
        shell: bash
        env:
          VERSION: "3.15.5"
        run: |
          curl -sSfL https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION-win64-x64.msi > cmake-installer.msi
      - name: "Install CMake"
        shell: cmd # msiexec fails when called from bash
        run: |
          msiexec /quiet /i cmake-installer.msi
          del cmake-installer.msi
      - name: "Install Wix"
        shell: bash
        run: |
          mkdir -p /c/wix
          cd /c/wix
          curl -sSfL https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip > wix-binaries.zip
          unzip wix-binaries.zip
          rm wix-binaries.zip
      - name: "Build archive"
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:/c/Strawberry/perl/bin:/c/Program Files/CMake/bin:$PATH"
          export RUSTFLAGS=-Ctarget-feature=+crt-static
          export FEATURES="default-msvc"
          export ARCHIVE_TYPE="zip"
          export KEEP_SYMBOLS="true"
          export RUST_LTO=""
          export TARGET="x86_64-pc-windows-msvc"
          export NATIVE_BUILD="true"
          make package
      - name: "Build package"
        shell: bash
        run: |
          export PATH="/c/wix:$PATH"
          ./scripts/package-msi.sh
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-pc-windows-msvc.zip
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-pc-windows-msvc.zip"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x64.msi
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x64.msi"

  deb-verify:
    needs:
      - build-x86_64-unknown-linux-gnu-packages
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: ["ubuntu:14.04","ubuntu:16.04","ubuntu:18.04","ubuntu:20.04","debian:8","debian:9","debian:10"]
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          apt-get update && \
          apt-get install -y \
          ca-certificates \
          curl \
          git \
          systemd \
          make
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: target/artifacts
      - name: First install of DEB package.
        run: |
          dpkg -i target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb && vector --version
      - name: Second install of DEB package.
        run: |
          dpkg -i target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb && vector --version

  rpm-verify:
    needs:
      - build-x86_64-unknown-linux-gnu-packages
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: ["centos:7","centos:8","amazonlinux:1","amazonlinux:2","fedora:33"]
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          yum update -y && \
          yum install -y \
          ca-certificates \
          curl \
          git \
          systemd \
          tar \
          make
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name:  vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm
          path: target/artifacts
      - name: First install of RPM package.
        run: |
          rpm -i --replacepkgs target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm && vector --version
      - name: Second install of RPM package.
        run: |
          rpm -i --replacepkgs target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm && vector --version

  osx-verify:
    runs-on: macos-10.15
    needs:
      - build-x86_64-apple-darwin-packages
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name:  vector-${{ env.VECTOR_VERSION }}-x86_64-apple-darwin.tar.gz
          path: target/artifacts
      - run: |
          tar -xvf target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-apple-darwin.tar.gz && vector-x86_64-apple-darwin/bin/vector --version

  release-failure:
    name: release-failure
    if: failure()
    needs:
      - build-x86_64-unknown-linux-gnu-packages
      - build-x86_64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-gnu-packages
      - build-x86_64-apple-darwin-packages
      - build-x86_64-pc-windows-msvc-packages
      - build-armv7-unknown-linux-gnueabihf-packages
      - build-armv7-unknown-linux-musleabihf-packages
      - deb-verify
      - rpm-verify
      - osx-verify
    runs-on: ubuntu-20.04
    steps:
      - run: echo Failed
